
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 17;
  public static final int NE = 21;
  public static final int LT = 20;
  public static final int ELSE = 10;
  public static final int PLUS = 15;
  public static final int RBRACE = 28;
  public static final int RPAREN = 26;
  public static final int INT = 6;
  public static final int CTE_STRING = 32;
  public static final int SEMI = 22;
  public static final int WHILE = 11;
  public static final int CTE_INT = 33;
  public static final int END = 4;
  public static final int CTE_FLOAT = 34;
  public static final int IF = 9;
  public static final int LBRACE = 27;
  public static final int LPAREN = 25;
  public static final int COLON = 24;
  public static final int GT = 19;
  public static final int ID = 31;
  public static final int PROGRAM = 2;
  public static final int DO = 12;
  public static final int COMMA = 23;
  public static final int FLOAT = 7;
  public static final int UPLUS = 29;
  public static final int EOF = 0;
  public static final int MAIN = 3;
  public static final int DIV = 18;
  public static final int MINUS = 16;
  public static final int PRINT = 13;
  public static final int error = 1;
  public static final int ASSIGN = 14;
  public static final int VOID = 8;
  public static final int VAR = 5;
  public static final int UMINUS = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "MAIN",
  "END",
  "VAR",
  "INT",
  "FLOAT",
  "VOID",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "PRINT",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "GT",
  "LT",
  "NE",
  "SEMI",
  "COMMA",
  "COLON",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "UPLUS",
  "UMINUS",
  "ID",
  "CTE_STRING",
  "CTE_INT",
  "CTE_FLOAT"
  };
}

